apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  loadBalancerIP: ${WG_SERVICE_IP}
  ports:
    - port: 51822
      targetPort: 51822
      protocol: UDP
      name: wireguard
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: vps-metrics
  selector:
    app: wireguard
