apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: ${WG_SERVICE_IP}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 51822
      targetPort: 51822
      protocol: UDP
      name: wireguard
  selector:
    app: wireguard
