apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: siyuan
  namespace: siyuan
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "siyuan"
    # Authentik Authentication
    nginx.ingress.kubernetes.io/auth-url: "http://authentik-proxy-outpost.siyuan.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://siyuan.xzr.es/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid"
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
spec:
  ingressClassName: nginx
  rules:
    - host: siyuan.xzr.es
      http:
        paths:
          - path: /outpost.goauthentik.io/
            pathType: Prefix
            backend:
              service:
                name: authentik-proxy-outpost
                port:
                  number: 9000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: siyuan
                port:
                  number: 80