apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-configmap
data:
  BASE_URL: "https://mealie.home.lab"
  ALLOW_SIGNUP: "false"
  POSTGRES_HOST: "192.168.1.11"
  POSTGRES_USER: "mealie"
  POSTGRES_DB: "mealie"
