apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - ../../base/mealie
  - configmap.yaml
  - ingress.yaml
secretGenerator:
- name: mealie-secrets
  literals:
    - POSTGRES_PASSWORD=your-db-password-here
configMapGenerator:
- name: mealie-configmap
  literals:
    - BASE_URL=https://mealie.home.lab
    - ALLOW_SIGNUP=false
